version: '3'

services:
  calculator:
    image: ursu/pipeline:ci-${CALCULATOR_BUILD_NUMBER}
    ports:
     - "80:80"
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
