version: '3.1'

services:
  calculator:
    image: ursu/pipeline:ci-${CALCULATOR_BUILD_NUMBER-10}
    #ports:
    # - "8080:80"
  integration:
    image: integrationtest:int-${BUILD_NUMBER-10}
    build: .
    environment:
      - TEAMCITY_PROJECT_NAME
